#spring.application.name: apigateway
     
server.port: 8866
    


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        discovery.locator: 
           enabled: true
           lowerCaseServiceId: true
        routes:
        - id: indexservice
        uri: lb://indexservice
        predicates: 
        - Path=/index/**
        filters: 
        - RewritePath=/index/(?<path>.*), /$\{path}

server.ssl:
  key-store: apigateway.jks
  key-store-password: spring_demo
  key-alias: apigateway
 

       
